client_id=""
client_secret=""
kubernetes_server="https://67.58.53.146:6443"
redirect_url="https://k8s.optiputer.net/oidc-auth/callback"
issuer="https://test.cilogon.org"

sessionAuthKey=""
sessionEncKey=""
