client_id=""
client_secret=""
pub_client_id=""
pub_client_secret=""
oidc_provider="https://cilogon.org"
cluster_url="k8s.example.com"
cluster_name="kubernetes"

session_auth_key="" # 32 byte random string
session_enc_key="" # 32 byte random string

email=""
email_smtp=""
email_port=465
email_username=""
email_password=""
