client_id=""
client_secret=""
# kubernetes_server="https://67.58.53.146:6443"
kubernetes_server="https://67.58.51.37:6443"
redirect_url="https://k8s.prism.optiputer.net/callback"
issuer="https://test.cilogon.org"
cluster_url="http://k8s.prism.optiputer.net"

sessionAuthKey=""
sessionEncKey=""
storage_path="/storage"
