required = ["k8s.io/code-generator/cmd/client-gen"]

[[override]]
  name = "github.com/stretchr/testify"
  version = "v1.2.1"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.10.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v7.0.0"

[[constraint]]
name = "k8s.io/code-generator"
version = "kubernetes-1.10.0"

[[constraint]]
name = "github.com/prometheus/client_golang"
version = "v0.8.0"

[[constraint]]
name = "github.com/go-mail/mail"
version = "v2"
