required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.9.3"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v6.0.0"

[[constraint]]
name = "k8s.io/code-generator"
version = "kubernetes-1.9.3"
