apiVersion: v1
kind: ServiceAccount
metadata:
  name: nautilus-portal
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nautilus-portal
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: nautilus-portal
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: nautilus-portal
  name: nautilus-portal
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: nautilus-portal
    spec:
      serviceAccountName: nautilus-portal
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: nautilus-portal
        image: us.gcr.io/prp-k8s/nautilus-portal:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: portal-config
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: nautilus-portal
  name: nautilus-portal
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: nautilus-portal
