apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oidc-auth
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /oidc-auth
        backend:
          serviceName: oidc-auth
          servicePort: 80
