apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-auth-admin
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: oidc-auth-admin
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: oidc-auth-admin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: oidc-auth
  name: oidc-auth
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: oidc-auth
    spec:
      serviceAccountName: oidc-auth-admin
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: oidc-auth
        image: us.gcr.io/prp-k8s/oidc-auth:bigdipa
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: portal-pv-storage
          mountPath: /storage
      # nodeSelector:
      #   routable: "true"
      volumes:
      - name: config-volume
        configMap:
          name: portal-config
      - name: portal-pv-storage
        nfs:
          server: 67.58.53.150
          path: "/Data/suncave-nfs"
      # - name: portal-pv-storage
      #   persistentVolumeClaim:
      #    claimName: portal-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: oidc-auth
  name: oidc-auth
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: oidc-auth
# ---
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: standard
#   namespace: kube-system
# provisioner: kubernetes.io/nfs
# parameters:
#   type: nfs
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nfs
# spec:
#   capacity:
#     storage: 100Gi
#   accessModes:
#     - ReadWriteMany
#   storageClassName: standard
#   nfs:
#     server: 67.58.53.150
#     path: "/Data/suncave-nfs"
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: portal-pv-claim
#   namespace: kube-system
# spec:
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
