# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: oidc-auth-admin
# ---
# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1beta1
# metadata:
#   name: oidc-auth-admin
# subjects:
# - kind: ServiceAccount
#   name: oidc-auth-admin
#   namespace: default
# roleRef:
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: rbac.authorization.k8s.io
# ---
apiVersion: extensions/v1beta1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: oidc-auth
  name: oidc-auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: oidc-auth
    spec:
      # serviceAccountName: oidc-auth-admin
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: oidc-auth
        image: us.gcr.io/prp-k8s/oidc-auth:latest
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: oidc-auth
  name: oidc-auth
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: oidc-auth
