apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-auth-admin
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: oidc-auth-admin
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: oidc-auth-admin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: oidc-auth
  name: oidc-auth
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: oidc-auth
    spec:
      serviceAccountName: oidc-auth-admin
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: oidc-auth
        image: us.gcr.io/prp-k8s/oidc-auth:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /config.toml
      nodeSelector:
        routable: "true"
      volumes:
      - name: config-volume
        configMap:
          name: portal-config
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: oidc-auth
  name: oidc-auth
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: oidc-auth
